version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgres/data/
    env_file:
      - infra/.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - django_poll

  django_poll:
    image: viator3m/django_poll:v1.0
    command:
      - /start
    volumes:
      -  static:/app/static/
      -  media:/app/media/
    depends_on:
      - db
    env_file:
      - infra/.env

volumes:
  static:
  media:
  postgres:
